@startuml
left to right direction
[*] --> 電源オン : 電源を入れる
電源オン --> 右旋回開始 : 光センサーが黒いライン上
電源オン --> 左旋回開始 : 光センサーがラインから外れる
右旋回開始 --> 左旋回開始 :光センサーがラインから外れる
左旋回開始 --> 右旋回開始 :光センサーが黒いライン上
右旋回開始 --> [*] : 電源を切る
左旋回開始 --> [*] : 電源を切る
@enduml